### ISSUE TITLE
Make mobile work

### ISSUE THREAD

**Issue by joelongstreet** [joelongstreet/data-forms#13]
Come up with some abbreviated version that works on mobile

**Comment by joelongstreet** [comment]
# ToDo
- [x] Settings editor should be hid in a hamburger menu
- [x] Create a better favicon
- [x] Legend should have a background color and always be behind settings editor
- [x] Preview should have a background color
- [x] Drop the border radius on everything
- [x] Footer should be hidden behind a menu
- [x] Smaller header
- [x] Examples page should feature 2 items in a row
- [ ] Make touching an example always bring up the next image
- [x] Example popover should be 90% of page width

**Comment by joelongstreet** [comment]
fixed with mobile branch merge
